apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
type: Opaque
data:
  DB_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==  # base64 encoded value of 'mysecretpassword'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: my-namespace
data:
  app-config.yaml: |
    database:
      user: myuser
      password: mypassword
    server:
      host: localhost
      port: 8080
