apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: my-namespace
spec:
  capacity:
    storage: 5Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Allows multiple pods to access the volume at the same time
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc  
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b4d11b3e4567890a #Efs ID

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  storageClassName: efs-sc  
